insert into freelancer (freelancer_id, first_name, last_name, email_address) values ('1', 'John', 'Woo', 'johnwoo@example.com');
insert into freelancer_skills (freelancer_freelancer_id, skills) values ('1', 'Java');
insert into freelancer_skills (freelancer_freelancer_id, skills) values ('1', 'Python');
insert into freelancer_skills (freelancer_freelancer_id, skills) values ('1', 'SQL');
insert into freelancer (freelancer_id, first_name, last_name, email_address) values ('2', 'Joss', 'Whedon', 'josswhedon@example.com');
insert into freelancer_skills (freelancer_freelancer_id, skills) values ('2', '.Net Core');
insert into freelancer_skills (freelancer_freelancer_id, skills) values ('2', 'SQL');
insert into freelancer (freelancer_id, first_name, last_name, email_address) values ('3', 'Gary', 'Dauberman', 'gary@example.com');
insert into freelancer_skills (freelancer_freelancer_id, skills) values ('3', 'Python');
insert into freelancer_skills (freelancer_freelancer_id, skills) values ('3', 'ML');